splash = true
wallpaper {
    monitor = DP-2
    path = /home/xuhan/Pictures/wallpapers/MID_AUTUMN_FESTIVAL.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/xuhan/Pictures/wallpapers/COFFEE.jpg
    fit_mode = cover
}
