# 状态栏背景和前景颜色
set -g status-style "bg=#7c571c,fg=#ffffff"

# 未激活窗口标签颜色
setw -g window-status-style "bg=#7c571c,fg=#ffffff"

# 当前激活窗口标签颜色
setw -g window-status-current-style "bg=#615597,fg=#ffffff"

# 面板（Pane）边框颜色
set -g pane-border-style "fg=#7c571c"
set -g pane-active-border-style "fg=#615597"

# 提示信息和命令模式颜色
set -g message-style "bg=#685e30,fg=#ffffff"
