background = {{ colors.background.default.rgb}}
base = {{ colors.surface.default.rgb }}
text = {{ colors.on_surface.default.rgb }}
alternate_base = {{ colors.surface_variant.default.rgb }}
bright_text = {{ colors.on_surface_variant.default.rgb }}
accent = {{ colors.primary.default.rgb }}
accent_secondary = {{ colors.secondary.default.rgb }}

# h1_size
# h2_size
# h3_size
# font_size = 20
# small_font_size
icon_theme = "Tela-circle"
font_family = "Google Sans"
font_family_monospace = "FiraCode Nerd Font"
# rounding_large
# rounding_small
