# --- 基础配色 ---
background #1a1209
foreground #f0e0d0
cursor     #ccbdff
cursor_text_color #342565

# --- 标签栏 ---
active_tab_background   #ccbdff
active_tab_foreground   #342565
inactive_tab_background #534432
inactive_tab_foreground #d9c3ab

# --- 16色终端阵列 ---

# Black (Surface / Surface Variant)
color0 #1a1209
color8 #534432

# Red (Error)
color1 #ffdad6
color9 #ffb4ab

# Green (利用 MD3 的 Tertiary 或自定义映射)
color2 #eebf79
color10 #614004

# Yellow (Inverse Primary 或 Secondary)
color3 #d3c78f
color11 #4f471b

# Blue (Primary)
color4 #ccbdff
color12 #4b3c7d

# Magenta (Custom / Outline)
color5 #a18d78
color13 #534432

# Cyan (Inverse Surface)
color6 #635497
color14 #f0e0d0

# White (On Surface)
color7 #f0e0d0
color15 #d9c3ab

# --- 选中后的文字颜色 ---
selection_background #ccbdff
selection_foreground #342565
