# --- 基础配色 ---
background #f2fbfe
foreground #141d1f
cursor     #7d5700
cursor_text_color #ffffff

# --- 标签栏 ---
active_tab_background   #7d5700
active_tab_foreground   #ffffff
inactive_tab_background #d4e5ea
inactive_tab_foreground #3a494d

# --- 16色终端阵列 ---

# Black (Surface / Surface Variant)
color0 #f2fbfe
color8 #d4e5ea

# Red (Error)
color1 #410002
color9 #ba1a1a

# Green (利用 MD3 的 Tertiary 或自定义映射)
color2 #1e6776
color10 #abedfe

# Yellow (Inverse Primary 或 Secondary)
color3 #5e5a7d
color11 #e4dfff

# Blue (Primary)
color4 #7d5700
color12 #ffdeaa

# Magenta (Custom / Outline)
color5 #6a7a7e
color13 #b9c9ce

# Cyan (Inverse Surface)
color6 #f2be62
color14 #293234

# White (On Surface)
color7 #141d1f
color15 #3a494d

# --- 选中后的文字颜色 ---
selection_background #7d5700
selection_foreground #ffffff
