# --- 基础配色 ---
background #fff8f5
foreground #26190f
cursor     #924c00
cursor_text_color #ffffff

# --- 标签栏 ---
active_tab_background   #924c00
active_tab_foreground   #ffffff
inactive_tab_background #f7dece
inactive_tab_foreground #544338

# --- 16色终端阵列 ---

# Black (Surface / Surface Variant)
color0 #fff8f5
color8 #f7dece

# Red (Error)
color1 #410002
color9 #ba1a1a

# Green (利用 MD3 的 Tertiary 或自定义映射)
color2 #755b1a
color10 #ffdf9d

# Yellow (Inverse Primary 或 Secondary)
color3 #785830
color11 #ffddb7

# Blue (Primary)
color4 #924c00
color12 #ffdcc4

# Magenta (Custom / Outline)
color5 #877366
color13 #dac2b3

# Cyan (Inverse Surface)
color6 #ffb780
color14 #3c2d23

# White (On Surface)
color7 #26190f
color15 #544338

# --- 选中后的文字颜色 ---
selection_background #924c00
selection_foreground #ffffff
